# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt5 import QtCore, QtGui, QtWidgets
from Use_Case_2_Local import Ui_Form_Local
from Use_Case_2_Remote import Ui_Form_Remote
from Use_Case_2_Remote_Ask import Ui_Form_AskCred
#from Use_Case_2_CheckConnection import Ui_Form_CheckCred
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtGui import QIcon
from pypsrp.powershell import PowerShell, RunspacePool
from pypsrp.wsman import WSMan
from cryptography.fernet import Fernet
#from Credential import Cred
import os
from Logs import Log 


class Ui_Form_main(object):
    def __init__(self):
        self.temp_flag=None
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 400)
        Form.setStyleSheet("background-color: rgb(0, 80, 50);")
        self.msg = QMessageBox()



        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(60, 50, 500, 200))
        self.label.setPixmap(QtGui.QPixmap(os.getcwd()+"\\status.jpg"))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(130, 280, 170, 51))
        self.pushButton.setStyleSheet("background-color: rgb(204, 153, 255);\n"
"font: 75 14pt \"Times New Roman\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 280, 170, 51))
        self.pushButton_2.setStyleSheet("background-color: rgb(204, 153, 255);\n"
"font: 75 14pt \"Times New Roman\";")
        self.pushButton_2.setObjectName("pushButton_2")

        
        
        

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Team 2: Select Machine"))
        #Form.setWindowTitle("Team:2 Samba Share UseCase")
        Form.setWindowIcon(QIcon(os.getcwd()+'\\team2.png'))
        Form.setWindowOpacity(0.95)
        self.pushButton.setText(_translate("Form", "Local-Machine"))
        self.pushButton.clicked.connect(self.Call_Local)
        self.pushButton_2.setText(_translate("Form", "Remote-Machine"))
        self.pushButton_2.clicked.connect(self.Call_Remote)
       
        





    def Call_Local(self):
        loc=Log('###---###---###----###------------          USER HAS OPT FOR LOCAL MACHINE     -------- ###---###---###----###---')

        
        self.Form = QtWidgets.QWidget()
        self.ui = Ui_Form_Local(self.Form)
        self.ui.setupUi(self.Form)
        self.Form.show()
        
    def Call_Remote(self):
        loc=Log(' ###---###---###----###----------------      USER HAS OPT FOR REMOTE MACHINE ---------- ###---###---###----###---')

        def get_Cred():
            # if self.ui_2.flag ==1 and ((self.ui_2.UserName != self.USERNAME) or (self.ui_2.IP!=self.ip) or (self.ui_2.Password !=self.PASSWORD)):
            #     self.msg.setStyleSheet("background-color: rgb(171,235,198);")
            #     self.msg.setText("*********You Have Entered Wrong Credential.*************")
            #     self.msg.setWindowTitle("Status")
            #     self.msg.setIcon(QMessageBox.Information)
            #     self.msg.exec_()
            if self.ui_2.flag==1:
                self.Form_3 = QtWidgets.QWidget()
                self.ui = Ui_Form_Remote(self.Form_3,self.ui_2.UserName,self.ui_2.Password,self.ui_2.IP)
                self.ui.setupUi(self.Form_3)
                self.Form_3.show()
                



    
            
        self.Form = QtWidgets.QWidget()
        self.ui_2 = Ui_Form_AskCred(self.Form)
        self.ui_2.setupUi(self.Form)
        self.Form.show()
    

        # def get_Flag():
        #     print('amol')
        #     print(self.ui_2.flag)
        #     self.temp_flag = self.ui_2.flag
            #if self.ui_2.flag==1:
                #self.ui_2.pushButton.clicked.connect(get_Cred)
        #----------------------self.ui_2.pushButton.clicked.connect(get_Cred)
        
        #if self.ui_2.flag==1:
            #print('amol')
        self.ui_2.pushButton.clicked.connect(get_Cred)





if __name__ == "__main__":
    import ctypes, sys
    # import sys
    # app = QtWidgets.QApplication(sys.argv)
    # Form2 = QtWidgets.QWidget()
    # ui2 = Ui_Form_main()
    # ui2.setupUi(Form2)
    # Form2.show()
    # sys.exit(app.exec_())
    
    def is_admin():
        try:
            return ctypes.windll.shell32.IsUserAnAdmin()
        except:
            return False

    if is_admin():
        # Code of your program here
        import sys
        from datetime import date

        


        app = QtWidgets.QApplication(sys.argv)
        Form2 = QtWidgets.QWidget()
        ui2 = Ui_Form_main()
        ob=Log('************************************ Application Started************************************** **********')
        ui2.setupUi(Form2)
        Form2.show()
        sys.exit(app.exec_())
    else:
        # Re-run the program with admin rights
        ctypes.windll.shell32.ShellExecuteW(None, "runas", sys.executable, " ".join(sys.argv), None, 1)
    

'''
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form2 = QtWidgets.QWidget()
    ui2 = Ui_Form_main()
    ui2.setupUi(Form2)
    Form2.show()
    sys.exit(app.exec_())

'''