# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'front.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLineEdit
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtCore import QDate

from pypsrp.powershell import PowerShell, RunspacePool
from pypsrp.wsman import WSMan
from Logs import Log
#from Credential import Cred


class Ui_Form_AskCred(object):
    def __init__(self,obc):
        self.flag=0
        self.flag_2=0
        self.obc = obc
        self.UserName=None
        self.Password = None
        #self.OBJ = Cred()
        #self.PASSWORD = self.OBJ.PASSWORD
        #self.ip = self.OBJ.ip
        #self.USERNAME = self.OBJ.USERNAME
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 400)
        Form.setWindowOpacity(0.99)
        Form.setStyleSheet("background-color: rgb(0,0,0)")
        self.msg = QMessageBox()

        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")

        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout.setContentsMargins(30, 30, 30, 30)
        self.horizontalLayout.setSpacing(30)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.textChanged.connect(self.Enable_Button)


        

        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)

        font_date = QtGui.QFont()
        font_date.setFamily("Times New Roman")
        font_date.setPointSize(20)

        self.lineEdit.setFont(font)
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)

        


        
      


       


        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout_2.setContentsMargins(30, 30, 30, 30)
        self.horizontalLayout_2.setSpacing(30)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)


        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setFont(font)

        self.lineEdit_2.textChanged.connect(self.Enable_Button)


        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(30, 30, 30, 30)
        self.horizontalLayout_3.setSpacing(30)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)


        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setEnabled(True)
        self.lineEdit_3.setInputMask("")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.textChanged.connect(self.Enable_Button)


        self.horizontalLayout_3.addWidget(self.lineEdit_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setFont(font)
        self.pushButton.setEnabled(False) 
        self.pushButton.clicked.connect(self.Make_Connection)
        
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Team 2"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;color:#ffffff\">Host IP Address :</span></p></body></html>"))
        
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;color:#ffffff\">Remote Machine UserName :</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;color:#ffffff\">Remote Machine Password :</span></p></body></html>"))
        self.lineEdit.setStyleSheet("color:#ffffff")
        self.lineEdit_3.setStyleSheet("color:#ffffff")
        self.lineEdit_2.setStyleSheet("color:#ffffff")

        self.pushButton.setText(_translate("Form", "Submit"))
        self.pushButton.setStyleSheet("color:#D827E3")
        self.pushButton.setStyleSheet("QPushButton"
                             "{"
                             "background-color : #2798E3;"
                             "}"
                             "QPushButton::pressed"
                             "{"
                             "background-color :#ffffff;"
                             "}"
                             "{"
                             "font-size :40px;"
                             "}"
                             )

    def Enable_Button(self):
        self.pushButton.setEnabled(bool(self.lineEdit.text()) and bool(self.lineEdit_2.text()) and bool(self.lineEdit_3.text()))
        #loc=Log('User Restarted Service {}'.format(self.lineEdit.text()))


    def Make_Connection(self):

        self.UserName = self.lineEdit_2.text()
        self.Password = self.lineEdit_3.text()
        self.IP = self.lineEdit.text()
        loc=Log('(: User has Requested to make Connection with Remote Machine with IP Address {} and Machine Name as {}'.format(self.IP,self.UserName))
        try:

            self.wsman = WSMan(self.IP, username= self.UserName,password=self.Password,cert_validation=False,ssl=False,operation_timeout=3000,connection_timeout=5000,read_timeout=5000)
            with self.wsman,RunspacePool(self.wsman) as pool:
                self.P = PowerShell(pool)
            self.msg.setStyleSheet("background-color: rgb(171,235,198);")
            self.msg.setText("*********:(Connection Established.:(*************")
            self.msg.setWindowTitle("Status")
            self.msg.setIcon(QMessageBox.Information)
            self.msg.exec_()
            self.flag=1
            self.obc.close()
            loc=Log(' Connection with Remote Machine with IP Address {} and Machine Name as {} is ***SuccessFull***'.format(self.IP,self.UserName))
            print("------------------------------------Connection Establicshed------------------------------")
        except Exception as ex:
            self.msg.setStyleSheet("background-color: rgb(171,235,198);")
            self.msg.setText("*:)Connection Failed.:)* Check Network Connection or Entered Correct Credential")
            self.msg.setWindowTitle("Status")
            self.msg.setIcon(QMessageBox.Information)
            self.msg.exec_()
            self.obc.close()
            loc=Log(' Connection with Remote Machine with IP Address {} and Machine Name as {} is ***Failed***'.format(self.IP,self.UserName))



# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Form2 = QtWidgets.QWidget()
#     ui2 = Ui_Form_AskCred(Form2)
#     ui2.setupUi(Form2)
#     Form2.show()
#     sys.exit(app.exec_())
